### ISSUE TITLE
Use github actions to build the libraries.

### ISSUE THREAD

**Issue by cloudwebrtc** [webrtc-sdk/webrtc-build#1]
The local compilation is a repetitive and boring thing. These should be handed over to CI. When we create a release tag, we compile it into a binary package available for all platforms, which can avoid the security risks caused by uploading binary files locally.

But this task is not simple. If you have any experience in compiling webrtc source code with GitHub actions, please help me

**Comment by huang12zheng** [comment]
I don't have weBRTC experience
I don't know the webrTC source code either.

But I have a experience with libgit2,
github action file is: https://github.com/huang12zheng/libgit2/blob/main/.github/workflows/release.yml

> I'll also take a look at WebRTC, but there might be a lot of blocking

**Comment by huang12zheng** [comment]
* question
I find that there is existing a action in github
https://github.com/shiguredo-webrtc-build/webrtc-build/blob/master/.github/workflows/build.yml
so, why we need to rework?

**Comment by cloudwebrtc** [comment]
@huang12zheng Yes, Shiguredo’s compilation script is a good example, but this repo has added a lot of custom patches. Unlike Shiguredo, we need to compile the dynamic link library to ensure that the minimum binary size native SDK is provided to flutter-webrtc.

**Comment by cloudwebrtc** [comment]
Hey @huang12zheng, If you are interested in this, I will be very happy to accept PR to resolve this issue.
Currently, we need to compile `libwebrtc.aar` for Android:
Include
`armeabi-v7a` `arm64-v8a` `x86_64` `x86`

Darwin platform include
`iOS armv7`
`iOS arm64`
`iOS x64 simulator`
`iOS arm64 simulator`
`macOS x64`
`macOS arm64`
Combine all the above platforms into `WebRTC.xframework` and compress them into `WebRTC.xcframework.zip`

Windows/Linux/ARM Linux:
You need to clone https://github.com/webrtc-sdk/libwebrtc to the source directory during compilation and generate it. The dynamic link library of `libwebrtc.{so,dll}`.

**Comment by huang12zheng** [comment]
Thank you for your reply. I am trying
@cloudwebrtc

**Comment by huang12zheng** [comment]
I am indeed very sorry that I I give up going on. I feel awful about it and want show something.
* In [ci-demo](https://github.com/huang12zheng/ci-demo/blob/main/.github/workflows/source.yaml) I want to build without using run.py.
1. Build image for something about linux
> However, it too big for image, which can’t pull again(would get 503 error). So, I can't reuse it. I must just build and run rightnow. it is the same with Shiguredo. That's reason one.
2.  Build script ,which follow by this issue.
> It can’t work simple. Action would run build in [place](https://github.com/huang12zheng/ci-demo/tree/main/ci/build) if I had downloaded from source, but script need  some debug. It might just need to modify these scripts. But I am sorry for that I don't have the time or the ability to do that.

* I also do [patch](https://github.com/huang12zheng/webrtc-action/blob/use_lib/apply_patch.py) for Shiguredo’s example.
Patch’s info is as follow:
1. Use min patch and add libwebrtc.
2. faster_clone than Shiguredo’s
3. container_preparations_advance, This is just a shift
  4. fix_window_scriptinvocationpath_error, just due to my workspace is different with Shiguredo’s
But when I compile libwebrtc, it get some [error](https://github.com/huang12zheng/webrtc-action/actions/runs/1666711351)

Finally, I apologize for some reason above. I don't want to do it for a while.
